services:
  concert-diary:
    container_name: 'concert-diary'
    environment:
      - SESSION_COOKIE_SECRET=${SESSION_COOKIE_SECRET}
      - REGISTER_TOKEN=${REGISTER_TOKEN}
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '~/concert-diary:/app/data'
    restart: unless-stopped
    ports:
      - '${PORT}:3000'
