name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: test and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup ssh
        run: |
          mkdir ~/.ssh
          cd ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > known_hosts
          chmod 600 ~/.ssh/id_ed25519
      - name: execute shell script on server
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} ${{ vars.DEPLOY_SCRIPT }}
